project:
  type: default
  resources:
    - figs

format:
  html:
    toc: true
    css: templates/styles.css
  pdf:
    documentclass: article
    number-sections: true
    include-in-header:
       text: |
        \usepackage{xcolor}
        \usepackage{lscape}
        \newcommand{\blandscape}{\begin{landscape}}
        \newcommand{\elandscape}{\end{landscape}}
        \usepackage{geometry}
        \geometry{
          top=2.5cm,
          bottom=2.5cm,
          left=2.5cm,
          right=2.5cm
        }
  docx:
    reference-doc: templates/custom-reference.docx
    number-sections: true
  revealjs:
    slide-number: true
    css: templates/styles.css

bibliography: refs/references.bib

editor: visual

